name: Frist Workspace
on:
  push:
   branches:
     - main
jobs:
  frist-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "Hello World"

      - name: Checkout Repo
        uses: actions/checkout@v6.0.2

      - name: List Repo Files
        run: ls -a 
